stocks:
  - AAPL
  - MSFT
  - AMZN

forex:
  - "EURUSD=X"
  - "GBPUSD=X"
  - "AUDUSD=X"

indices:
  - "^GSPC"
  - GLD
  - USO

intervals:
  - 1d
  - 1h
  - 15m

periods:
  1d: 1501d
  1h: 1y
  15m: 60d

params:
  DMAC:
    short_ema: [5, 10, 20, 50]
    long_ema: [30, 200]
    adx_period: [7, 14]
    adx_threshold: [20, 25]
  
  RSI_MA:
    ma: [50, 100, 200]
    buy_rsi: [35, 40, 50]
    sell_rsi: [35, 40, 50, 75]

  BBANDS_MR:
    bb_len: [20, 30]
    bb_k: [2.0, 2.5]
    rsi_os: [30, 35]
    adx_max: [20]
    stop_atr: [1.5, 2.0]
    max_hold_bars: [20]

  DONCHIAN_BO:
    entry_len: [20, 40]
    exit_len: [10, 20]
    atr_len: [14]
    entry_buffer_atr: [0.0, 0.25]
    stop_atr: [2.0]
    trail_atr: [3.0]
    max_hold_bars: [100]
    cooldown_bars: [0, 5]

  RSI_PULLBACK:
    trend_len: [90, 100, 110]
    slope_lookback: [5]
    rsi_len: [14, 21]
    rsi_pullback: [40]
    rsi_recover: [50]
    atr_len: [14]
    stop_atr: [2.0]
    max_hold_bars: [55, 60, 65]
  ATR_VOL_BO:
    atr_len: [12, 14, 16]
    atr_expansion_mult: [1.2, 1.3, 1.5]
    stop_atr: [1.8, 2.0, 2.5]
    breakout_len: [3]
    max_hold_bars: [50, 100]

INTERVAL_TO_TIMEFRAME:
  "1m": Minutes
  "5m": Minutes
  "15m": Minutes
  "30m": Minutes
  "1h": Minutes
  "4h": Minutes
  "1d": Days
  "1wk": Weeks

commission: 0.0
sizer: 50
