stocks:
  - AAPL
  - MSFT
  - AMZN

forex:
  - "EURUSD=X"
  - "GBPUSD=X"
  - "AUDUSD=X"

indices:
  - "^GSPC"
  - GLD
  - USO

intervals:
  - 1d
  - 1h
  - 15m

periods:
  1d: 5y
  1h: 1y
  15m: 60d

strategies:
  dmac:
    short_ema: [5, 10, 20, 50]
    long_ema: [30, 100, 200]

  rsi:
    period: [14, 21]
    overbought: [70]
    oversold: [30]

  macd:
    fast: [12]
    slow: [26]
    signal: [9]


commission: 0
sizer: 50
starting_capital: 1000